Forward the initial HaProxyMessage in KafkaAuthnHandler and release HAProxyMessage when closing the channel
kroxylicious/kroxylicious pull request #1308
Opened 2024-06-13 06:35 UTC by luozhenyu

### Type of change

- Bugfix

### Description

1. Forward the initial HaProxyMessage in KafkaAuthnHandler. When both HAProxyMessageDecoder and KafkaAuthnHandler are added to the pipeline, an HAProxyMessage will be rejected by KafkaAuthnHandler with a `new IllegalStateException("Unexpected message class io.netty.handler.codec.haproxy.HAProxyMessage")`
2. Release HAProxyMessage when closing the channel. 
```txt
ERROR 2024-06-13 12:02:03.403 v1(6) ResourceLeakDetector.java:337 _ _ _ _ _ [IOUringEventLoopGroup-5-1] LEAK: HAProxyMessage.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
``` 

### Additional Context

_Why are you making this pull request?_

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [x] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

2024-06-13 08:06 UTC, k-wall commented
Thank you! I hope to have time to review this over the next couple of days.

2024-06-18 19:21 UTC, k-wall commented
@luozhenyu I think the code changes look reasonable.

One question - you are relaying the HA PROXY frame to the upstream.  Apache Kafka does understand the HA Proxy protocol so I am wondering what purpose this serves.  What is the upstream in your case?

2024-06-18 19:27 UTC, k-wall commented on kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaAuthnHandler.java
> +            ctx.fireChannelRead(msg);
I think this should be configurable. Ordinarily the upstream will be Apache Kafka which doesn't understand the HA Proxy protocol.   So this should be something the user has to be enable.

2024-07-31 08:50 UTC, showuon commented
@luozhenyu , could you reply to the questions @k-wall raised when available?

2024-08-14 04:23 UTC, SamBarker requested changes
Given upstream Kafka brokers don't support the HA proxy protocol I don't think we should forward it by default. So I think we need to make it configurable before merging.

2024-08-14 04:23 UTC, SamBarker commented on kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java
> +    private <T extends ReferenceCounted> T track(T obj) {
I think / would hope the netty leak detector extension would provide the same assurance 

Annotating this test with `@ExtendWith(NettyLeakDetectorExtension.class)` should do the job.

2024-08-14 04:23 UTC, SamBarker commented on kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/KafkaAuthnHandlerTest.java
> +    }
There are two completely independent assertions here, can we split them into two different test cases.

2024-08-28 09:24 UTC, showuon commented
Since we didn't get response from the author for 2 months, we're going to close it. Welcome to re-open it if you have free cycle to work on it @luozhenyu . Thanks for your contribution!

2024-08-28 09:24 UTC, closed without merging